### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by danieljonasson123** [calebnance/table-tennis-manager#1]
Hi! Thanks for the work! I´m a newbie and having diffuculties installting the table-tennis-manager. I have copied all the contents to /var/www/html. I also created a database named ttm_2014 and executed the -sql for creating tables. When opening any webpage I´m redirected to /install/install/wizard.php page. That folder does not exist. If I make a copy of that folder within the install folder I manage to open the wizard page. But when entering the database host, name, user and password nothing happens. Am I doing anything wrong? 

Best regards Daniel

**Comment by calebnance** [comment]
Hi Daniel,

No, this is actually something I am still working on so that you can do everything from the GUI, instead of messing with any files. Have you went through the wizard process? This could be a bug still :-/

**Comment by danieljonasson123** [comment]
Hi! Thanks for replying! I haven´t managed to get past the wizard. Nothing happens after filling in the database parameters. When trying to open any other page I´m redirected to the wizard page.

**Comment by calebnance** [comment]
Okay, that means I haven't pushed up my latest code -_- Sorry about that. For now, if you want, go to the 'includes/helper.php' file and at the start of the function isInstalled(), add this line: return true; And you should be able to bypass this for now. It's definitely a work in progress, I haven't worked on it in a couple weeks.

**Comment by danieljonasson123** [comment]
Cool! Many thanks!

**Comment by calebnance** [comment]
This should be fixed now!
